import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FCardStyle cardStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FCardStyle(
  decoration: BoxDecoration(
    border: Border.all(color: colors.border),
    borderRadius: style.borderRadius,
    color: colors.background,
  ),
  contentStyle: FCardContentStyle(
    titleTextStyle: typography.xl2.copyWith(
      fontWeight: FontWeight.w600,
      color: colors.foreground,
      height: 1.5,
    ),
    subtitleTextStyle: typography.sm.copyWith(color: colors.mutedForeground),
  ),
);

class PharmaCardStyles extends ThemeExtension<PharmaCardStyles> {
  const PharmaCardStyles({required this.primary, required this.borderless});

  final FCardStyle primary;
  final FCardStyle borderless;

  @override
  PharmaCardStyles copyWith({FCardStyle? primary, FCardStyle? borderless}) =>
      PharmaCardStyles(
        primary: primary ?? this.primary,
        borderless: borderless ?? this.borderless,
      );

  @override
  PharmaCardStyles lerp(ThemeExtension<PharmaCardStyles>? other, double t) {
    if (other is! PharmaCardStyles) {
      return this;
    }
    return PharmaCardStyles(
      primary: _lerpCardStyle(primary, other.primary, t),
      borderless: _lerpCardStyle(borderless, other.borderless, t),
    );
  }
}

PharmaCardStyles buildCardStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  final base = cardStyle(colors: colors, typography: typography, style: style);
  final borderless = base.copyWith(
    decoration: BoxDecoration(
      color: colors.background,
      borderRadius: style.borderRadius,
    ),
  );
  return PharmaCardStyles(primary: base, borderless: borderless);
}

extension PharmaCardStylesExtension on FThemeData {
  PharmaCardStyles get cardStyles => extension<PharmaCardStyles>();
}

FCardStyle _lerpCardStyle(FCardStyle a, FCardStyle b, double t) {
  return t < 0.5 ? a : b;
}
