include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # === DOCUMENTATION ===
    public_member_api_docs: false

    # === STYLE ===
    lines_longer_than_80_chars: false

    # === I/O ===
    avoid_print: true

analyzer:
  # NOTE: custom_lint plugin temporarily disabled - requires Flutter 3.40+
  # plugins:
  #   - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mapper.dart"
    - "**/*.drift.dart"
    - "**/*.drift.types.temp.dart"
    - "**/*.expr.temp.dart"
    - "**/*.types.temp.dart"
    - ".dart_tool/**"
    - "tool/**"
    - "lib/core/database/generated/dao_references.dart"  # Reference-only, not meant to compile

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  enable-experiment:
    - dot-shorthands

  errors:
    missing_return: error
    dead_code: error
    always_use_package_imports: error
    avoid_print: error
    unnecessary_lambdas: warning
