targets:
  $default:
    builders:
      drift_dev:
        # disable drift's default builder, we're using the modular setup instead.
        enabled: false

      # Instead, enable drift_dev:analyzer and drift_dev:modular manually:
      drift_dev:analyzer:
        enabled: true
        generate_for:
          include:
            - lib/core/database/**/*.dart
            - lib/core/database/**/*.drift
        options: &options
          # Drift build options, as per https://drift.simonbinder.eu/docs/advanced-features/builder_options/
          store_date_time_values_as_text: true
          named_parameters: true
          generate_manager: true
          sql:
            dialect: sqlite
            options:
              version: "3.39"
              modules: [fts5, json1]
              known_functions:
                normalize_text: "text(text)"
      drift_dev:modular:
        enabled: true
        generate_for:
          include:
            - lib/core/database/**/*.dart
            - lib/core/database/**/*.drift
        # We use yaml anchors to give the two builders the same options
        options: *options
      riverpod_generator:
        generate_for:
          include:
            - lib/**/providers/**/*.dart
            - lib/**/viewmodels/**/*.dart
            - lib/core/services/**/*.dart
            - lib/core/router/**/*.dart
          exclude:
            - test/**/*
            - integration_test/**/*
            - tool/**/*
            - lib/**/widgets/**/*
            - lib/**/presentation/widgets/**/*
            - lib/**/presentation/ui/**/*
            - lib/**/theme/**/*
      dart_mappable_builder:
        generate_for:
          include:
            - lib/core/mappers/**/*.dart
            - lib/core/models/**/*.dart
            - lib/core/utils/**/*.dart
            - lib/**/domain/**/*.dart
            - lib/**/entities/**/*.dart
            - lib/**/models/**/*.dart
            - lib/**/providers/**/*.dart
        options:
          caseStyle: camelCase
          generateMethods:
            - decode
            - encode
            - copy
            - stringify
            - equals
          renameMethods:
            fromMap: fromJson
            fromJson: fromJsonString
            toMap: toJson
            toJson: toJsonString
          generateInitializerForScope: package

