targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_manager: true
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
              known_functions:
                normalize_text: "text(text)"
      riverpod_generator:
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - test/**/*
            - integration_test/**/*
            - tool/**/*
      dart_mappable_builder:
        options:
          caseStyle: camelCase
          generateMethods:
            - decode
            - encode
            - copy
            - stringify
            - equals

