targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
              known_functions:
                normalize_text: "text(text)"

