targets:
  $default:
    builders:
      # --- DRIFT (Modular Setup) ---
      # Restriction removed to ensure all .drift and .dart table files are found.
      drift_dev:
        enabled: false

      drift_dev:analyzer:
        enabled: true
        options: &drift_options
          store_date_time_values_as_text: true
          named_parameters: true
          generate_manager: true
          sql:
            dialect: sqlite
            options:
              version: "3.39"
              modules: [fts5, json1]
              known_functions:
                normalize_text: "text(text)"

      drift_dev:modular:
        enabled: true
        options: *drift_options

      # --- RIVERPOD ---
      # Optimized: Ignores UI, Tests, and Tooling
      riverpod_generator:
        generate_for:
          include:
            - lib/core/providers/**.dart
            - lib/core/services/**.dart
            - lib/core/database/providers.dart
            - lib/core/router/router_provider.dart
            - lib/features/**/providers/**.dart
            - lib/features/**/viewmodels/**.dart
          # Exclude UI widgets explicitly

      # --- AUTO ROUTE ---
      # Scope to router + screen folders (no cached builds to avoid stale outputs)
      auto_route_generator:auto_route_generator:
        enabled: true
        generate_for:
          - lib/core/router/app_router.dart
          - lib/features/**/screens/**.dart
          - lib/features/**/views/**.dart
      auto_route_generator:auto_router_generator:
        enabled: true
        generate_for:
          - lib/core/router/app_router.dart

      # --- DART MAPPABLE ---
      # Optimized: Broad inclusion but excludes UI/Tests
      dart_mappable_builder:
        generate_for:
          include:
            - lib/core/models/**.dart
            - lib/features/**/domain/models/**.dart
            - lib/features/**/domain/entities/**.dart
            - lib/features/**/presentation/providers/**.dart
            - lib/features/**/presentation/viewmodels/**.dart
        options:
          caseStyle: camelCase
          generateMethods:
            - decode
            - encode
            - copy
            - stringify
            - equals
          renameMethods:
            fromMap: fromJson
            fromJson: fromJsonString
            toMap: toJson
            toJson: toJsonString
          generateInitializerForScope: package
