targets:
  $default:
    builders:
      drift_dev:
        enabled: false

      drift_dev:analyzer:
        enabled: true
        generate_for:
          exclude:
            - integration_test/**
            - test/**
        options: &drift_options
          store_date_time_values_as_text: true
          named_parameters: true
          generate_manager: true
          sql:
            dialect: sqlite
            options:
              version: "3.39"
              modules: [fts5, json1]
              known_functions:
                normalize_text: "text(text)"

      drift_dev:modular:
        enabled: true
        options: *drift_options

      riverpod_generator:
        generate_for:
          include:
            - lib/core/providers/**.dart
            - lib/core/services/**.dart
            - lib/core/network/**.dart
            - lib/core/database/providers.dart
            - lib/app/router/router_provider.dart
            - lib/features/**/providers/**.dart
            - lib/features/**/viewmodels/**.dart

      auto_route_generator:auto_route_generator:
        enabled: true
        generate_for:
          - lib/app/router/app_router.dart
          - lib/features/**/screens/**.dart
          - lib/features/**/views/**.dart

      auto_route_generator:auto_router_generator:
        enabled: true
        generate_for:
          - lib/app/router/app_router.dart

      dart_mappable_builder:
        generate_for:
          include:
            - lib/core/models/**.dart
            - lib/features/**/domain/models/**.dart
            - lib/features/**/domain/entities/**.dart
            - lib/features/**/presentation/providers/**.dart
            - lib/features/**/presentation/viewmodels/**.dart
        options:
          caseStyle: camelCase
          generateMethods: [decode, encode, copy, stringify, equals]
          renameMethods:
            fromMap: fromJson
            fromJson: fromJsonString
            toMap: toJson
            toJson: toJsonString
          generateInitializerForScope: package
