include: ../analysis_options.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_final_locals: false
    unawaited_futures: false

analyzer:
  errors:
    avoid_print: ignore
    unawaited_futures: ignore
    unused_import: warning