// test/core/parser/data_driven_parser_test.dart

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:pharma_scan/core/parser/medicament_grammar.dart';
import 'package:pharma_scan/core/utils/medicament_helpers.dart';

void main() {
  final parser = MedicamentParser();

  test('Parsing Challenges File Validation', () async {
    // 1. Read the CSV file generated by python script
    final file = File('data_validation/smart_parsing_challenges.csv');
    if (!await file.exists()) {
      // Skip if file not generated
      return;
    }

    final lines = await file.readAsLines();
    var warnings = 0;
    var criticalFailures = 0;

    // Skip CSV header row
    for (final line in lines.skip(1)) {
      if (line.trim().isEmpty) {
        continue;
      }

      // Parse CSV line (semicolon-separated)
      final parts = line.split(';');
      if (parts.length < 4) {
        continue;
      }

      // category = parts[0] (not used in assertions)
      final rawName = parts[1];
      final officialForm = parts.length > 2 ? parts[2] : '';
      final officialLab = parts.length > 3 ? parts[3] : '';
      // official_dosage is at index 4, but we don't use it for parsing

      // Pass knowledge-injected hints to parser
      final result = parser.parse(
        rawName,
        officialForm: officialForm.isEmpty ? null : officialForm,
        officialLab: officialLab.isEmpty ? null : officialLab,
      );

      // === ASSERTIONS FOR ROBUSTNESS ===

      // 0. KNOWLEDGE-INJECTED VALIDATION: Official form and lab should NOT be in baseName
      if (result.baseName != null) {
        if (officialForm.isNotEmpty) {
          // Normalize for comparison (case-insensitive, remove extra whitespace)
          final normalizedForm = officialForm.trim().toUpperCase();
          final normalizedBaseName = result.baseName!.toUpperCase();

          // Check if any significant word from official form appears in baseName
          // Split form into words and check each (ignore very short words like "de", "en", etc.)
          final formWords = normalizedForm
              .split(RegExp(r'\s+'))
              .where((word) => word.length > 2)
              .toList();

          for (final word in formWords) {
            if (normalizedBaseName.contains(word)) {
              debugPrint(
                'WARNING: Official form word "$word" found in baseName for: "$rawName" -> "${result.baseName}"',
              );
              warnings++;
              break;
            }
          }
        }

        if (officialLab.isNotEmpty) {
          // Use the real parseMainTitulaire function instead of reimplementing it
          final mainLab = parseMainTitulaire(officialLab).toUpperCase();
          final normalizedBaseName = result.baseName!.toUpperCase();

          // Split into words and check each significant word
          final labWords = mainLab
              .split(RegExp(r'\s+'))
              .where((word) => word.length > 2)
              .toList();

          for (final word in labWords) {
            if (normalizedBaseName.contains(word)) {
              debugPrint(
                'WARNING: Official lab word "$word" found in baseName for: "$rawName" -> "${result.baseName}"',
              );
              warnings++;
              break;
            }
          }
        }
      }

      // 1. Name should not contain standalone numbers (unless part of a molecule like "T-4")
      // This catches failed dosage extractions like "500 mg" left in name
      // We allow hyphenated numbers (e.g. INTERLEUKINE-2) and numbers followed by a word
      // (e.g. "ACCUSOL 35 POTASSIUM" where "35" is part of the name)
      // Also allow medication names like "A 313" where the number is part of the name
      if (result.baseName != null) {
        // Special case: "A 313" is a valid medication name
        final isLetterNumberMedication = RegExp(
          r'^[A-Z]\s+\d{1,4}$', // Match "A 313" pattern
          caseSensitive: false,
        ).hasMatch(result.baseName!.trim());

        // Match numbers that are not hyphenated and not followed by a word (even with spaces)
        // This excludes cases like "ACCUSOL 35 POTASSIUM" where "35" is part of the name
        // The regex checks if number is followed by whitespace and then a letter (word)
        final hasStandaloneNumber = RegExp(
          r'(?<!-)\b\d+\b(?!\s*[a-zA-Z])(?!-)',
        ).hasMatch(result.baseName!);

        if (hasStandaloneNumber && !isLetterNumberMedication) {
          debugPrint(
            'WARNING: Number left in name for: "$rawName" -> "${result.baseName}"',
          );
          warnings++;
        }

        // 2. Name should not contain Units
        // Use a subset of dosageUnits that are clear indicators of leakage (common dosage units)
        // Note: We exclude less common units that might appear in medication names legitimately
        final criticalUnits = ['mg', 'ml', 'mL', 'UI', 'U.I.', 'M.U.I.', '%'];
        final unitsPattern = criticalUnits
            .map((unit) => RegExp.escape(unit))
            .join('|');
        final hasUnit = RegExp(
          r'\b(' + unitsPattern + r')\b',
          caseSensitive: false,
        ).hasMatch(result.baseName!);
        if (hasUnit) {
          debugPrint(
            'CRITICAL: Unit leaked into name: "$rawName" -> "${result.baseName}"',
          );
          criticalFailures++;
        }
      }

      // 3. Formulation should be detected (most lines in your file have forms)
      // except specifically known weird ones.
      if (!rawName.toUpperCase().contains('GAVISCON') &&
          !rawName.toUpperCase().contains('DEGRÉ DE DILUTION')) {
        if (result.formulation == null) {
          debugPrint('WARNING: Formulation missed for: "$rawName"');
          warnings++;
        }
      }

      // 4. Ratio Detection logic check
      if (rawName.contains('/')) {
        // Check if it starts with a dosage pattern (simplified check for leading ratio)
        // Use the real dosageUnits list from the parser to avoid duplication
        final unitsPattern = MedicamentGrammarDefinition.dosageUnits
            .map((unit) => RegExp.escape(unit))
            .join('|');
        final leadingRatioPattern = RegExp(
          r'\d+\s*(?:' + unitsPattern + r')\s*/',
          caseSensitive: false,
        );
        if (leadingRatioPattern.hasMatch(rawName)) {
          final hasRatio = result.dosages.any((d) => d.isRatio);
          if (!hasRatio && result.dosages.isNotEmpty) {
            debugPrint('WARNING: Ratio missed in "$rawName"');
            warnings++;
          }
        }
      }

      // 5. Context extraction: Lines with context keywords should have them in contextAttributes
      // Use the real contextKeywords list from the parser to avoid duplication
      for (final keyword in MedicamentGrammarDefinition.contextKeywords) {
        if (rawName.toUpperCase().contains(keyword)) {
          final foundInContext = result.contextAttributes.any(
            (attr) => attr.toUpperCase() == keyword,
          );
          if (!foundInContext) {
            debugPrint(
              'WARNING: Context keyword "$keyword" not extracted from: "$rawName"',
            );
            warnings++;
          }
        }
      }

      // 6. Multi-ingredient detection: Lines with molecule separators should have isMultiIngredient == true
      // Exclude dosage ratios (handled above)
      // Use the real dosageRatioPattern from the parser to avoid duplication
      final hasSlash = rawName.contains('/');
      final hasPlus = rawName.contains('+');
      final hasDosageRatio = MedicamentGrammarDefinition.dosageRatioPattern()
          .hasMatch(rawName);

      // Exclude special cases that are NOT multi-ingredient (matching parser logic)
      final upperName = rawName.toUpperCase();
      final isAmoxicillineClavulanique =
          upperName.contains('AMOXICILLINE') &&
          upperName.contains('ACIDE CLAVULANIQUE');
      final isMinirin =
          upperName.contains('MINIRIN') &&
          (upperName.contains('MICROGRAMMES') ||
              upperName.contains('MICROGRAMMES/ML'));
      final isUnitSlashPattern = RegExp(
        r'\b(unités|unité|unités|unité|microgrammes|mg|g|ml|mL|ui|UI)\s*/\s*(ml|mL|L|l)\b',
        caseSensitive: false,
      ).hasMatch(rawName);
      final isMedicationWithNumber = RegExp(
        r'\b[A-Z]+\s+\d+\s+[A-Z]+\b', // Match "ACCUSOL 35 POTASSIUM"
        caseSensitive: false,
      ).hasMatch(rawName);
      final isFlexpen =
          upperName.contains('FLEXPEN') ||
          upperName.contains('UNITÉS/ML') ||
          upperName.contains('UNITES/ML');

      if ((hasSlash && !hasDosageRatio) || hasPlus) {
        // Check if it's likely a molecule separator (alphabetic words around / or +)
        final moleculePattern = RegExp(
          r'\b[A-Za-z]+\s*[/+]\s*[A-Za-z]+',
          caseSensitive: false,
        );
        if (moleculePattern.hasMatch(rawName)) {
          // Exclude known false positives
          if (!isAmoxicillineClavulanique &&
              !isMinirin &&
              !isUnitSlashPattern &&
              !isMedicationWithNumber &&
              !isFlexpen) {
            if (!result.isMultiIngredient) {
              debugPrint(
                'WARNING: Multi-ingredient not detected in: "$rawName"',
              );
              warnings++;
            }
          }
        }
      }
    }

    debugPrint('\n=== Validation Summary ===');
    debugPrint('Total warnings: $warnings');
    debugPrint('Critical failures: $criticalFailures');

    // Fail on warnings too, now that we fixed the parser logic
    expect(
      criticalFailures + warnings,
      0,
      reason:
          'Parser quality check failed. Warnings detected in parsing logic.',
    );
  });
}
