// backend_pipeline/tool/generate_fixtures.ts
// Generates normalization test fixtures for cross-language parity
import { writeFile } from 'fs/promises';
import { normalizeForSearch } from '../src/sanitizer';

const FIXTURES = [
  'DOLIPRANE®',
  'Paracétamol 500mg',
  'Amoxicilline/Acide clavulanique',
  'Ibuprofène 200mg',
  'Éphédrine HCl',
  'N-Acétyl cystéine',
  'ACIDE ASCORBIQUE',
  'œstrogène',
  'ß-bloquant',
  'Caféïne',
  'Hydroxychloroquine',
  'Ácido acetilsalicílico',
  'N-acétyl-L-cystéine',
  'Acide folique',
  'N,N-diméthyltryptamine',
  'L-tryptophane',
  'α-tocophérol',
  'γ-aminobutyrique',
  'D-glucose',
  'L-glutamine',
  'N-acétylglucosamine',
  'N-acétyl-D-glucosamine',
  'N-acétylneuraminique',
  'N-acétyl-L-tyrosine',
  'N-acétyl-L-méthionine',
  'N-acétyl-L-leucine',
  'N-acétyl-L-cystéine',
  'N-acétyl-L-tryptophane',
  'N-acétyl-L-phénylalanine',
  'N-acétyl-L-histidine',
  'N-acétyl-L-arginine',
  'N-acétyl-L-aspartate',
  'N-acétyl-L-glutamate',
  'N-acétyl-L-glutamine',
  'N-acétyl-L-proline',
  'N-acétyl-L-serine',
  'N-acétyl-L-threonine',
  'N-acétyl-L-valine',
  'N-acétyl-L-isoleucine',
  'N-acétyl-L-lysine',
  'N-acétyl-L-ornithine',
  'N-acétyl-L-citrulline',
  'N-acétyl-L-glutathione',
  'N-acétyl-L-carnosine',
  'N-acétyl-L-anserine',
  'N-acétyl-L-homocysteine',
  'N-acétyl-L-hydroxyproline',
  'N-acétyl-L-tyrosylglycine',
  'N-acétyl-L-phenylalanylalanine',
  'N-acétyl-L-tryptophylglycine',
  'N-acétyl-L-phenylalanylserine',
  'N-acétyl-L-phenylalanylthreonine',
  'N-acétyl-L-phenylalanylvaline',
  'N-acétyl-L-phenylalanylproline',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
  'N-acétyl-L-phenylalanylglutamine',
  'N-acétyl-L-phenylalanylglutamate',
  'N-acétyl-L-phenylalanylglutathione',
];

async function main() {
  const results = FIXTURES.map(input => ({
    input,
    output: normalizeForSearch(input)
  }));
  await writeFile(
    new URL('../assets/normalization_fixtures.json', import.meta.url),
    JSON.stringify(results, null, 2),
    'utf-8'
  );
  console.log('Wrote normalization_fixtures.json with', results.length, 'cases.');
}

main();
